# Generated by Django 5.2 on 2025-04-14 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='pdf_content',
        ),
        migrations.CreateModel(
            name='BookFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_content', models.FileField(upload_to='books/pdfs/')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_files', to='books.book')),
            ],
        ),
    ]
